def _throw(self, error):

    def throw():
        raise error
    return throw
