def test_check_exclusives(self):
    (a, b, c, d, e) = self.setupTargets()
    context = Context(CheckExclusivesTest.config, options={}, run_tracker=None, target_roots=[d, e])
    check_exclusives_task = CheckExclusives(context, signal_error=True)
    try:
        check_exclusives_task.execute([d, e])
        self.fail('Expected a conflicting exclusives exception to be thrown.')
    except TaskError:
        pass
